name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create .env.local
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env.local
          echo "SESSION_PASSWORD=${{ secrets.SESSION_PASSWORD }}" >> .env.local

      - name: Build project
        run: npm run build
