name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # change this to your node version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo 'No tests yet
        # If you don't have tests yet, you can comment out this step or replace with "echo 'No tests yet'"

      - name: Build project
        run: npm run build
        # If your project does not have a build step, you can comment this out
